name: ansible-lint

description: run ansible-lint on the repository

inputs:
  project_dir: 
    description: The directory where the ansible project is located
    required: true
    default: ansible
  config_file:
    description: The path to the .ansible-lint.yml config file
    required: false
    default: .ansible-lint.yml
  args:
    description: Further arguments to ansible-lint
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project_dir }}
    - ${{ inputs.config_file }}
    - ${{ inputs.args }}